---
title: "Evaluating integrating SO models fit on designs generated by design optimization algorithm."
data: today
author: Max Savery
format: pdf
---

```{r set-up}
library(ggplot2)
library(dplyr)
library(viridis)
library(cmdstanr) 
library(bayesplot)
library(openxlsx)
library(stringr)
library(readr)

#working_dir <- "C:\\Users\\msavery\\OneDrive - UGent\\Documents\\ghent_phd_spatial_doe\\code\\optimal_design_site_occ"
working_dir <- "."
po_path <- file.path(working_dir, "data", "sim_data", "misspec")
result_path <- "C:\\Users\\msavery\\OneDrive - UGent\\Documents\\ghent_phd_spatial_doe\\data\\globus_hpc_collection\\exp_5_misspec"
source(file.path(working_dir, "experimental_design_functions.R"))
source(file.path(working_dir, "presence_only_functions.R"))
stan_models_path <- file.path(working_dir, "stan_models", "stan_site_occupancy_models.R")
source(stan_models_path)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)

# Hardcode all run names, sorry :(
experiment_files <- c("oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0.01_oracle",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0.01_sequential_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0.01_sequential_no_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0.05_oracle",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0.05_sequential_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0.05_sequential_no_int",
  #"oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0.1_oracle",
  #"oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0.1_sequential_int",
  #"oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0.1_sequential_no_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0_oracle",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0_sequential_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-0.25_p-0.2_misspec-0_sequential_no_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0.01_oracle",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0.01_sequential_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0.01_sequential_no_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0.05_oracle",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0.05_sequential_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0.05_sequential_no_int",
  #"oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0.1_oracle",
  #"oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0.1_sequential_int",
  #"oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0.1_sequential_no_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0_oracle",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0_sequential_int",
  "oe_model-3_sites-5_n-3_peak-5_a--2_b-0.5_g-1_d-2_p-0.2_misspec-0_sequential_no_int"
)
```

```{r param-setup}
k <- 20
sites <- k^2
m <- 5
n <- 3
design_reps <- 10
data_reps <- 10
n_surveys <- rep(n, m)
sigma <- 1
visits <- 3
p_0 <- 0.2
deviation <- 5
mcmc_iter <- 2000
n_chains <- 3
centroid <- c(10,4)
centroid_2 <- c(18,18)
link_func <- "cloglog"

# Data gen params are the same here.
alpha <- -2
beta <- 0.5

model_path <- "misspec_fits.stan"
model_string <- poisson_process_site_occupancy
write(model_string, model_path)
model_so <- cmdstan_model(model_path) 
```

```{r fits}
all_params <- c("alpha", "beta", "gamma", "delta")
gen_params <- c("occ_gen")
fit_matrix <- matrix(nrow=length(experiment_files), ncol=length(all_params))
v_matrix <- matrix(nrow=length(experiment_files), ncol=data_reps*design_reps)
chain_array <- array(dim=c(length(experiment_files), design_reps*data_reps*n_chains*mcmc_iter, length(all_params)))
gen_array <- array(dim=c(length(experiment_files), data_reps*design_reps, sites))
text_size <- 10

sampling_surface <- get_sampling_surface_donut(k, deviation)
sampling_surface <- get_bias_surface_exponential(sampling_surface, centroid)

for (e_i in 1:length(experiment_files)){
  # Get particular strength 
  print(paste("Current experiment: ", experiment_files[e_i]))
  param_split <- str_split(experiment_files[e_i], "_")
  misspec <- param_split[[1]][11]
  misspec <- as.numeric(str_split(misspec, "-")[[1]][2])
  delta <- param_split[[1]][9]
  delta <- as.numeric(str_split(delta, "-")[[1]][2])
  # Don't need to misspecification to fit the model but good to check it
  sampling_surface <- get_bias_surface_misspecified(sampling_surface, centroid_2, misspec)
  if (misspec == 0){
    sampling_surface$aux_e = rep(0, nrow(sampling_surface))
  }
  # Load PO data generated according to a certain level of misspecfication and set params
  if (!file.exists(file.path(po_path, paste("po_gen_ints-donut_peak=5_a=-2_b=", beta, "_g=1_d=", delta, "_e=", misspec, ".Rds", sep="")))){
    stop(paste("Check data ", po_path, "po_gen_ints-donut_peak=5_a=-2_b=", beta, "_g=1_d=", delta, "_e=", misspec, ".Rds", sep=""))
  }
  po_gen <- read_rds(file.path(po_path, paste("po_gen_ints-donut_peak=5_a=-2_b=", beta, "_g=1_d=", delta, "_e=", misspec, ".Rds", sep="")))
  if (!file.exists(file.path(result_path, experiment_files[e_i], "results.xlsx"))){
    stop(paste("Check run ", experiment_files[e_i], sep=""))
  }
  design_results <- read.xlsx(file.path(result_path, experiment_files[e_i], "results.xlsx"), sheet="best_sites")

  pa_eval_data <- generate_data_so(data_reps, sampling_surface, corr_matrix=NA, p_0, alpha, beta, sigma, visits, sites, link=link_func)
  
  # Check the data
  p <- ggplot(sampling_surface, aes(x, y, fill=aux_e)) + 
    geom_tile() +
    scale_fill_viridis(discrete=FALSE, name="E") +
    ggtitle(paste("Initial sampling surface, E covariate with misspec scale of ", misspec, sep="")) +
    theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
    coord_fixed()
  print(p)
  # Bias
  p <- ggplot(sampling_surface, aes(x, y, fill=po_gen$bias[data_reps,])) + 
    geom_tile() +
    scale_fill_viridis(discrete=FALSE, "Bias") +
    ggtitle(paste("Generated bias per site, misspec scale of ", misspec, sep="")) +
    theme(text=element_text(size=text_size), legend.key.size = unit(0.25, 'cm')) +
    coord_fixed()
  print(p)
  # Thinned bias
  thinned_intensity <- po_gen$lambda[data_reps,]*po_gen$bias[data_reps,]
  p <- ggplot() +
    geom_tile(sampling_surface, mapping=aes(x, y, fill=thinned_intensity, width=1, height=1), alpha=.6) + 
    scale_fill_viridis(discrete=FALSE, name="L*b") +
    ggtitle(paste("Generated PP thinning per site, \nincluding observed PO individuals, misspec scale=", misspec, sep="")) +
    geom_point(data=po_gen$Y_coords, mapping=aes(x=x, y=y), size=2, col="white") +
    theme(panel.grid.minor = element_line(colour="white")) +
    scale_y_continuous(breaks = seq(0, 20, 1)) +
    scale_x_continuous(breaks = seq(0, 20, 1)) +
    theme(text=element_text(size=text_size), legend.key.size = unit(0.25, 'cm')) +
    coord_fixed()
  print(p)
  # Iterate over designs and data reps
  # There will be d_i designs for the 10 random starts used in the experiments.
  chain_matrix <- matrix(nrow=0, ncol=length(all_params))
  iter_cnt <- 0
  for (d_i in 1:design_reps){
    d_rep_name <- paste("rand-start", d_i, sep="")
    site_idx <- design_results[[d_rep_name]]
    covars_sampled_sites <- sampling_surface[site_idx, ]
    # Then fit over the data reps
    for (data_rep in 1:data_reps){
      iter_cnt <- iter_cnt + 1
      selected_counts <- pa_eval_data$Y[data_rep, site_idx]
      data_site_occ = list(n_surveys=n_surveys, n_pa_sites=m, n_po_sites=sites, X=covars_sampled_sites$aux_x, Y=selected_counts, PO=po_gen$Y[1, ], X_po=sampling_surface$aux_x, Z_po=sampling_surface$aux_z, model_diag=0)
      fit_so_1 <- quiet(model_so$sample(data=data_site_occ, seed=13, chains=n_chains, iter_sampling=mcmc_iter, iter_warmup=500, refresh=0, show_messages=F)) 
      fit_draws <- fit_so_1$draws(all_params, format="matrix")
      chain_matrix <- rbind(chain_matrix, fit_draws)
      gen_occupancy <- fit_so_1$summary(variables="occ_gen")$mean
      v_est <- design_criteria(criteria="brier", sim_occ=gen_occupancy, obs_occ=pa_eval_data$Y)
      v_matrix[e_i, iter_cnt] <- v_est
      gen_array[e_i, iter_cnt, ] <- gen_occupancy
    }
  }
  fit_matrix[e_i, ] <- colMeans(chain_matrix)
  chain_array[e_i, ,] <- chain_matrix
}
```

```{r fit-inspect}
v_means <- rowMeans(v_matrix)
v_var <- apply(v_matrix, MARGIN=1, FUN=var)
exp_names <- c()
for (exp in 1:length(experiment_files)){
  param_split <- str_split(experiment_files[exp], "_")
  exp_name <- paste(param_split)
  beta <- param_split[[1]][7]
  delta <- param_split[[1]][9]
  misspec_id <- param_split[[1]][11:length(param_split[[1]])]
  exp_name <- paste(beta, "_", delta, "_", paste(misspec_id, collapse="_"), sep ="")
  exp_names <- c(exp_names, exp_name)
}
df <- data.frame(exp=exp_names, v_means=v_means, v_var=sqrt(v_var))
print(df)
```
A little too intense to look at all PPDs for $Y$.
```{r ppd}
#for (i in 1:length(experiment_files)){
#  for (j in 1:data_reps){
#    print(experiment_files[i])
#    generated_occ <- gen_array[i, j, ]
#    ppd_df <- data.frame(x=sampling_surface$x, y=sampling_surface$y, occ_rep=generated_occ)
#    
#    # Plot generated ys and thetas on the sampling grid
#    p <- ggplot(ppd_df, aes(x, y, fill=occ_rep)) + 
#        geom_tile() +
#        scale_fill_viridis(discrete=FALSE) +
#        ggtitle("PPD occupancy per site")
#    print(p)
#  }
#}
```