######################################################
# Script for optimal design of surveys for occupancy estimation
######################################################

library(ggplot2)
library(viridis)
#library(hrbrthemes)
library(cmdstanr) 
library(bayesplot)
library(dplyr)
library(tidyr)
library(reshape2)
library(spatstat)
library(parallel)
library(optparse)
library(openxlsx)

set.seed(13)

# R=1000 datasets for monte carlo approx
# Create command line arguments
parser <- OptionParser()
parser <- add_option(parser, "--working_dir", type="character", default=".", help="Path to the directory containing code to source for the main script")
parser <- add_option(parser, "--po_data_file", type="character", default="po_gen_ints-donut_a=-2_b=0.5_g=1_d=0.5.Rds", help="File name of PO data to use in optimization")
parser <- add_option(parser, "--exp_name", type="character", default="oe_run", help="Name of current experiment, which is used for dir to save output")
parser <- add_option(parser, "--use_sim_po", action="store_true", default=F, help="Use PO generated by simulation. Without this param, script expects real data to exist")
parser <- add_option(parser, "--data_reps", type="integer", default=4, help="Number of dataset reps for criterion estimation")
parser <- add_option(parser, "--m", type="integer", default=5, help="Number of sites to survey")
parser <- add_option(parser, "--max_visits", type="integer", default=5, help="Maximum number of time to visit each site")
parser <- add_option(parser, "--min_visits", type="integer", default=1, help="Minimum number of time to visit each site")
parser <- add_option(parser, "--vary_visits", action="store_true", default=F, help="Allow varying survey effort between sites")
parser <- add_option(parser, "--model_selection", type="integer", default=3, help="Occupancy model to use")
parser <- add_option(parser, "--random_starts", type="integer", default=3, help="Number of random starts to run the exchange")
parser <- add_option(parser, "--exch_iter", type="integer", default=3, 
                     help="Number of iterations of exchange before ending optimization. Recommended is 20 but default is set low for test runs.")
parser <- add_option(parser, "--mcmc_iter", type="integer", default=1000, help="Number of MCMC iterations in Stan")
parser <- add_option(parser, "--intensity_func", type="character", default="donut", help="Intensity function for sampling surface")
parser <- add_option(parser, "--bias_func", type="character", default="exponential", help="Bias function for sampling surface")
parser <- add_option(parser, "--p_logging", action="store_true", default=F, help="Boolean for logging information about posterior estimates")
parser <- add_option(parser, "--debug_stan", action="store_true", default=F, help="Boolean for turning on messages from stan model in nonparallel V")
parser <- add_option(parser, "--v_parallel", action="store_true", default=F, help="Boolean for parallel computation of V criterion")
parser <- add_option(parser, "--cores", type="integer", default=4, help="Number of cores to use for parallel processing")
parser <- add_option(parser, "--alpha", type="double", default=-2, help="Intercept for intensity")
parser <- add_option(parser, "--beta", type="double", default=0.5, help="Slope for intensity")
parser <- add_option(parser, "--gamma", type="double", default=1, help="Intercept for bias")
parser <- add_option(parser, "--delta", type="double", default=.5, help="Slope for bias")
parser <- add_option(parser, "--p", type="double", default=0.7, help="Probability of detection")
parser <- add_option(parser, "--area", type="integer", default=100, help="Area of region D")
parser <- add_option(parser, "--k", type="integer", default=20, help="Number of sites along one side of grid")
parser <- add_option(parser, "--aux_cor", type="double", default=0.8, help="Correlation between auxiliary covariates")


exp_args <- parse_args(parser)
print(exp_args)
# Really don't want to use this until later
stopifnot(exp_args$p_logging==F)

source(file.path(exp_args$working_dir, "experimental_design_functions.R"))
source(file.path(exp_args$working_dir, "presence_only_functions.R"))
stan_models_path <- file.path(exp_args$working_dir, "stan_models", "stan_site_occupancy_models.R")
source(stan_models_path)

exp_name <- exp_args$exp_name
exp_dir <- file.path(exp_args$working_dir, "experimental_runs", exp_name)
fig_dir <- file.path(exp_dir, "figures")
stan_dir <- file.path(exp_dir, "stan")
dir.create(exp_dir)
dir.create(fig_dir)
dir.create(stan_dir)
data_reps <- exp_args$data_reps
# Area for whole space, which allows us to set area for sites based on number of sites.
area_D <- exp_args$area
# For generating data according to GP
gp_bool <- F
# k is one side of grid
k <- exp_args$k
sites <- k^2
# alpha=2 indicates "good" quality of auxiliary information
alpha <- exp_args$alpha
beta <- exp_args$beta
gamma <- exp_args$gamma
delta <- exp_args$delta
p_0 <- exp_args$p
aux_cor <- exp_args$aux_cor
# This assumes spatial variance of 1, which was used in Reich 2018 (see supplement)
sigma <- 1
# There will be m sites selected for sampling
# 36/4 was used in paper
m <- exp_args$m
# Based on the size of grid get the auxiliary data and coordinates
# Because these don't really depend on any random variables and just location 
# in the grid, there will be one fixed dataset throughout the optimization
if (exp_args$intensity_func == "simple"){
  sampling_surface <- get_sampling_surface_simple(k)
}else{
  sampling_surface <- get_sampling_surface_donut(k)
  if (exp_args$bias_func == "exponential"){
    centroid <- c(10,4)
    sampling_surface <- get_bias_surface_exponential(sampling_surface, centroid)
  }else if (exp_args$bias_func == "correlation"){
    sampling_surface <- get_bias_surface_correlated(sampling_surface, aux_cor)
  }
  else{
    stop("Bias function not implemented")
  }
  # Filter for only a quarter of the grid.
  # If we filter, we need to change the total sites as well
  sites <- sites/4
  stopifnot(sites>m)
  sampling_surface <- sampling_surface %>% dplyr::filter(x<11, y<11)
}
print(sampling_surface)
corr_matrix <- specify_corr(sampling_surface[,1:2])

# Next, we use this data to generate the rest of the datasets
# The data generating function will sample R occupancy maps|params
# and then R complete datasets|occupancy maps'
# It turns out that if we want to compare different survey efforts it is convenient to have pre-generated datasets for
# each number of visits
# The number of surveys can differ between sites so it is a vector
# We will select m sites to have these visits, otherwise the sites will have 0 visits
# We will compare the number of visits during the optimization
link_func <- "cloglog"
if (exp_args$vary_visits == TRUE){
  visits <- c(exp_args$min_visits, exp_args$max_visits)
  print("Creating datasets for varying survey effort between sites")
  r_survey_data_n1 <- generate_data_so(data_reps, sampling_surface, corr_matrix, p_0, alpha, beta, sigma, visits[1], sites, link=link_func)
  r_survey_data_n5 <- generate_data_so(data_reps, sampling_surface, corr_matrix, p_0, alpha, beta, sigma, visits[2], sites, link=link_func)
} else{
  visits <- c(exp_args$max_visits)
  print("Creating datasets for fixed survey effort across sites")
  r_survey_data_n1 <- generate_data_so(data_reps, sampling_surface, corr_matrix, p_0, alpha, beta, sigma, visits[1], sites, link=link_func)
  r_survey_data_n5 <- generate_data_so(data_reps, sampling_surface, corr_matrix, p_0, alpha, beta, sigma, visits[1], sites, link=link_func)
}
print(paste("Current visit options:", paste(visits, collapse=" ")))

# Load pre-generated dataset or downloaded PO dataset.
if (exp_args$use_sim_po==T){
  r_po_data <- readRDS(file=file.path(exp_args$working_dir, 
                            "data", "sim_data", exp_args$po_data_file))
  Y_positive_indices <- which(r_po_data$Y>0)
  # This is the data at which there are counts > 0
  print("Data with counts > 0")
  print(r_po_data$Y[Y_positive_indices])
  # Subset based on datareps in this script
  # The PO data has been pregenerated with 96 reps, tho
  # we can regenerate
  r_po_data$Y <- r_po_data$Y[1:data_reps, ]
  stopifnot(r_po_data$params$alpha==alpha)
  stopifnot(r_po_data$params$beta==beta)
  stopifnot(r_po_data$params$gamma==gamma)
  stopifnot(r_po_data$params$delta==delta)
}else{
  stop("No other data source implemented in this script")
}
  
# For the coordinate exchange algorithm, we will need to precompute the nearest neighbors.
# I take a naive approach here of choosing the top l neighbors
l <- 4
nearest_neighbors <- get_neighbors(sampling_surface, l)
dim(nearest_neighbors)
nearest_neighbors

# Use the final generation iteration to look at the presence-absence and presence-only data
p <- ggplot(sampling_surface, aes(x, y, fill=aux_x)) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, name="X") +
  ggtitle("Initial sampling surface, X covariate") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("sampling_surface_aux_x.png", sep=""))
save_basic_plots(fig_name, p)

p <- ggplot(sampling_surface, aes(x, y, fill=aux_z)) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, name="Z") +
  ggtitle("Initial sampling surface, Z covariate") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("sampling_surface_aux_z.png", sep=""))
save_basic_plots(fig_name, p)

# Then plot PA data
p <- ggplot(sampling_surface, aes(x, y, fill=r_survey_data_n1$Y[data_reps,])) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, name="Counts") +
  ggtitle("Generated counts per site, sampling effort=1") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("counts-per-site_n1.png", sep=""))
save_basic_plots(fig_name, p)

p <- ggplot(sampling_surface, aes(x, y, fill=r_survey_data_n1$occupancy[data_reps,])) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, name="Occupancy") +
  ggtitle("Generated occupancy per site, sampling effort=1") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("occ-site_n1.png", sep=""))
save_basic_plots(fig_name, p)

p <- ggplot(sampling_surface, aes(x, y, fill=r_survey_data_n1$theta[data_reps,])) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, name="Theta") +
  ggtitle("generated occupancy probability per site, sampling effort=1") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("occ-p-site_n1.png", sep=""))
save_basic_plots(fig_name, p)

p <- ggplot(sampling_surface, aes(x, y, fill=r_survey_data_n5$Y[data_reps,])) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, name="Counts") +
  ggtitle("Generated counts per site, sampling effort=5") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("counts-per-site_n5.png", sep=""))
save_basic_plots(fig_name, p)

p <- ggplot(sampling_surface, aes(x, y, fill=r_survey_data_n5$occupancy[data_reps,])) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, name="Occupancy") +
  ggtitle("Generated occupancy per site, sampling effort=5") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("occ-site_n5.png", sep=""))
save_basic_plots(fig_name, p)

p <- ggplot(sampling_surface, aes(x, y, fill=r_survey_data_n5$theta[data_reps,])) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, name="Theta") +
  ggtitle("generated occupancy probability per site, sampling effort=5") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("occ-p-site_n5.png", sep=""))
save_basic_plots(fig_name, p)

# Then the PO data
p <- ggplot(sampling_surface, aes(x, y, fill=r_po_data$lambda[data_reps,])) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, name="Lambda") +
  ggtitle("Generated intensity per site") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("intensity-site.png", sep=""))
save_basic_plots(fig_name, p)

p <- ggplot(sampling_surface, aes(x, y, fill=r_po_data$bias[data_reps,])) + 
  geom_tile() +
  scale_fill_viridis(discrete=FALSE, "Bias") +
  ggtitle("Generated bias per site") +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("bias-site.png", sep=""))
save_basic_plots(fig_name, p)

thinned_intensity <- r_po_data$lambda[data_reps,]*r_po_data$bias[data_reps,]
p <- ggplot() +
  geom_tile(sampling_surface, mapping=aes(x, y, fill=thinned_intensity, width=1, height=1), alpha=.6) + 
  scale_fill_viridis(discrete=FALSE, name="L*b") +
  ggtitle("Generated PP thinning per site, \nincluding observed PO individuals") +
  geom_point(data=r_po_data$Y_coords, mapping=aes(x=x, y=y), size=2, col="white") +
  theme(panel.grid.minor = element_line(colour="white")) +
  scale_y_continuous(breaks = seq(0, 20, 1)) +
  scale_x_continuous(breaks = seq(0, 20, 1)) +
  theme(text=element_text(size=5), legend.key.size = unit(0.25, 'cm')) +
  coord_fixed()
fig_name <- file.path(fig_dir, paste("po-thinning-per-site.png", sep=""))
save_basic_plots(fig_name, p)

# We can experiment with these models in the exchange algorithm
# Model 1 uses just basic priors over params. Model 3 uses PO data as prior. Model 2
# uses different link function but is otherwise the same as model 1. Model has constant
# intensity, which doesn't make that much sense to use in this case.
model_strings <- list(
	"cloglog_site_occupancy"=cloglog_site_occupancy, 
	"site_occ_probit"=site_occupany_detection, 
	"poisson_poisson_prior"=poisson_process_site_occupancy, 
	"poisson_process_constant"=pp_site_occ_constant_no_po,
	"poisson_process_constant_po_prior"=pp_site_occ_constant_po
	)
model_selection <- exp_args$model_selection
model_name <- names(model_strings)[model_selection]
print(paste("Using model", model_name, model_selection))
model_path <- file.path(stan_dir, paste(model_name, ".stan", sep=""))
print(paste("Cmdstan model", model_strings[[model_selection]]))
write(model_strings[[model_selection]], model_path)
model <- cmdstan_model(model_path) 
# These are the parameters to report
# Only the PO prior model needs gamma and delta. 
# Then constant models need only alpha
if (model_selection==3){
  params <- c('p', 'alpha', 'beta', 'gamma', 'delta')
}else if ((model_selection==4)|(model_selection==5)){
  params <- c('p', 'alpha')
}else{
  params <- c('p', 'alpha', 'beta')
}
print(paste("Using params", paste(params, collapse=" ")))
generated_vars <- c('g_theta_gen', 'occ_gen')

# The reich paper repeats the entire exchange algorithm procedure 10 times,
# and retains solution with lowest V(D)
# Currently I am not repeating the procedure. However, it accounts for uncertainty associated with random m sites 
# selected for sampling
p_logging <- exp_args$p_logging
random_starts <- exp_args$random_starts
v_list <- vector(mode="list", length=random_starts)
names(v_list) <- c(1:random_starts)
best_v <- vector(mode="numeric", length=random_starts)
best_site_mat <- matrix(nrow=random_starts, ncol=m)
optimal_visit_mat <- matrix(nrow=random_starts, ncol=m)

# Initiate parallel processing if specified
if (exp_args$v_parallel==T){
  n_cores <- detectCores()
  print(paste("Using parallel processing. Cores detected: ", n_cores, ". Currently using ", exp_args$cores, " cores."))
  clust <- makeCluster(exp_args$cores)
  # Export the environment to the cluster
  clusterExport(clust, varlist=c("design_criteria", "brier_score_stan"), envir=environment())
}
# Start timer
start_time <- Sys.time()
for (r_start in 1:random_starts){
  print(paste("random initialization ", r_start, sep=""))
  # we first randomly select m sites, for each run of the exchange algorithm,
  # from the sampling surface, which includes the auxiliary information.
  # These sites will have n_i = n, the others will have n_i = 0
  # Only sites with n_i=n will contribute to likelihood for the site-occupancy model.
  if (r_start == 1){
    site_idx <- c(29, 30, 29, 40, 49)
  }else{
    site_idx <- sample(1:sites, m, replace=F)
  }
  # Initialize for exchange algorithm
  # I don't need best_neighbor_idx but it allows me to not modify the 
  # the vector that is looped over during the exchange. Even though this concurrent looping should be ok, as the sites are independently 
  # exchanged, but for organization purposes they are separate variables. 
  best_neighbor_idx <- site_idx
  # Vector to hold potential sampling effort at each site
  # optimal_visits will be initiated in algorithm
  possible_visits <- rep(visits[length(visits)], m)
  # Initial sites
  select_sites <- sampling_surface[site_idx,]
  # Convergence condition will be met where full iteration through all sampled sites results in no change
  # in sites. ie no changes in sites can improve criterion
  convergence_cond <- FALSE
  exchange_iter <- 0
  v_vec <- c()
  # Compute v for initial design
  # Not comparing sampling effort here
  print(select_sites)
  print("site idx")
  print(site_idx)
  print(r_survey_data_n5)
  if (exp_args$v_parallel==T){
    combined_df <- cbind(r_survey_data_n5$occupancy, r_survey_data_n5$Y, r_po_data$Y)
    estimate_vec <- parApply(clust, combined_df, 1, FUN=estimate_v_parallel, model, possible_visits, m, sites, sampling_surface, 
                                 site_idx, select_sites, generated_vars, model_selection, exp_args$mcmc_iter)
    # Compatible format with non-parallel v
    estimate_mat <- matrix(estimate_vec, nrow=data_reps, ncol=1)
  }
  else{
    estimate_mat <- estimate_v(model, possible_visits, data_reps, m, sites, sampling_surface, 
                               site_idx, select_sites, r_survey_data_n5, r_po_data,
                               p_logging, params, generated_vars, model_selection, exp_args$mcmc_iter, exp_args$debug_stan)
  }
  # Once the posterior is computed on each of R datasets, find the average score:
  new_v_est <- sum(estimate_mat) / data_reps
  print("Design score from initial exchange")
  print(new_v_est)
  v_vec <- c(v_vec, new_v_est)
  current_v_est <- new_v_est
  print("Initial row ids")
  print(site_idx)
  print("Initial coordinates")
  print(sampling_surface[site_idx,1:2])
  print("Initial design score")
  print(new_v_est)
  title <- paste("Inital spatial design: v=", round(new_v_est, 10), sep="")
  p <- plot_sites(sampling_surface, site_idx, title)
  fig_name <- file.path(fig_dir, paste("initial_design_", r_start, ".png", sep=""))
  ggsave(fig_name, plot=p, dpi=300, width=7, height=6, units="cm")
  
  while ((convergence_cond==FALSE) & (exchange_iter<=exp_args$exch_iter)){
    exchange_iter <- exchange_iter + 1
    print(paste("New exchange iteration: ", exchange_iter))
    # Data structure for each score estimate
    # Then compute the posterior based on those sites and generated data, for each r dataset
    # We iterate through the sites, computing the estimate of $V(D)$ for each so that we explore the effect of each site on the design
    for (s in 1:length(site_idx)){
      print(paste("ex iter: ", exchange_iter, ", current site index: ", s, sep=""))
      current_site <- site_idx[s]
      print(paste("current site: ", current_site, sep=""))
      neighbor_set <- nearest_neighbors[current_site,]
      # Set the current sites to the best from iteration over sites neighbors
      current_visits <- possible_visits
      # We first iterate through the neighbors of each site, and compute V for each exchange. 
      # The initial estimate will be for our initial design.
      for (visit in visits){
        n_count <- 0
        current_visits[s] <- visit
        for(nn in neighbor_set){
          # Handle duplicates in sites because the visit optimization is not compatible with 
          # the same site occurring multiple times in site_idx
          # Check that the neighbor isn't in the main set of sites
          if (nn %in% site_idx){
            print("skipping site")
            print(site_idx)
            print(nn)
            next
          }
          n_count <- n_count + 1
          # Select new data using the neighbors (switch out local points)
          neighbor_idx <- exchange_coordinates_deterministic(best_neighbor_idx, s, nn)
          select_sites <- sampling_surface[neighbor_idx,] 
          # Then set the survey effort for current id set
          # This code chunk will "double index" if the current site s already has been selected 
          # to have 1 visit, but that is ok since we just need the data at nn to correspond to 1 visit.
          # For example if possible_visits == c(1,5,5) and then we are the neighbor of the 1st site 
          # so that current_visits == c(1, 5,5) we will select that index==1 neighbor here 
          # If visits is fixed between sites this vector will always be of 0 length.
          visit_idx <- c(neighbor_idx[which(current_visits==exp_args$min_visits)])
          print("current s and site")
          print(s)
          print(current_site)
          print("current visit")
          print(visit)
          print("posible visits")
          print(possible_visits)
          print("current vistits")
          print(current_visits)
          print("ids with visit 1")
          print(visit_idx)
          r_survey_data <- r_survey_data_n5
          r_survey_data$occupancy[, visit_idx] <- r_survey_data_n1$occupancy[, visit_idx]
          r_survey_data$Y[, visit_idx] <- r_survey_data_n1$Y[, visit_idx]
          stopifnot(all(r_survey_data$Y[, visit_idx]<=exp_args$min_visits))
          # Check that we're selecting right sites
          if (visit==exp_args$min_visits){
            stopifnot(nn%in%visit_idx)
          }
          # Check that vector is empty if not varying visits
          if(exp_args$vary_visits==F){
            stopifnot(length(visit_idx)==0)
          }
          # Don't really need theta as it's only for data generation purposes
          r_survey_data$theta[, visit_idx] <- r_survey_data_n1$theta[, visit_idx]
          print("site set")
          print(site_idx)
          print("best neighbor idx")
          print(best_neighbor_idx)
          print("neighbors")
          print(neighbor_idx)
          print("current neighbor")
          print(nn)
          #print("current data selction after visits altered")
          #print(r_survey_data$Y[,neighbor_idx])
          if (exp_args$v_parallel==T){
            combined_df <- cbind(r_survey_data$occupancy, r_survey_data$Y, r_po_data$Y)
            estimate_vec <- parApply(clust, combined_df, 1, FUN=estimate_v_parallel, model, current_visits, m, sites, sampling_surface, 
                                         neighbor_idx, select_sites, generated_vars, model_selection, exp_args$mcmc_iter)
            # Compatible format with non-parallel v
            estimate_mat <- matrix(estimate_vec, nrow=data_reps, ncol=1)
          }
          else{
            estimate_mat <- estimate_v(model, current_visits, data_reps, m, sites, sampling_surface, 
                                       neighbor_idx, select_sites, r_survey_data, r_po_data,
                                       p_logging, params, generated_vars, model_selection, exp_args$mcmc_iter, exp_args$debug_stan)
          }
          # Once the posterior is computed on each of R datasets, find the average score:
          new_v_est <- sum(estimate_mat) / data_reps
          v_vec <- c(v_vec, new_v_est)
          
          if (new_v_est < current_v_est){
             current_v_est <- new_v_est
             title <- paste("New optimal spatial design: v=", round(new_v_est, 10), sep="")
             # Plot the new best site compared to the previous selection, but need to reverse arguments to function
             # Use current_visits as optimal visits.
             p <- plot_sites_vs_best(sampling_surface, current_site, best_neighbor_idx, neighbor_idx, possible_visits, current_visits, title)
             # Then set new best indices
             best_neighbor_idx <- neighbor_idx
             possible_visits <- current_visits
             print("New optimal row ids")
             print(best_neighbor_idx) 
             print("Optimum survey effort")
             print(possible_visits)
             print("New coordinates")
             print(sampling_surface[best_neighbor_idx,1:2])
             print("New optimal design score")
             print(current_v_est)
          }
          else{
            title <- paste("Non-optimal spatial design: v=", round(new_v_est, 10), 
                           "\nvs current optimal design: v=", round(current_v_est, 10), sep="")
            #print("No change in optimal design")
            p <- plot_sites_vs_best(sampling_surface, current_site, neighbor_idx, best_neighbor_idx, current_visits, possible_visits, title)
          }
          fig_name <- file.path(fig_dir, paste("site_locs_rand-start-", r_start, "_ex-iter_", 
                            exchange_iter, "_site-iter-", s, "_effort_", visit, "_nn-iter", n_count,".png", sep=""))
          ggsave(fig_name, plot=p, dpi=300, width=7, height=6, units="cm")
          # Then go to the next neighbor or site
        }
      }
      # Set design to best from iteration through visits AND neighbors for one site
      # If there is no change from any neighbors, site_idx will not change
      site_idx <- best_neighbor_idx
    }
    # If after a complete iteration through all the sites, the best sites haven't changed
    # then we can call that convergence
    # If it's the first iteration we need to initialize the best sites
    if(exchange_iter==1){
      best_iter_idx <- site_idx
      optimal_visits <- possible_visits
    }
    else if(all(best_iter_idx==site_idx)&all(optimal_visits==possible_visits)){
      convergence_cond <- TRUE
    }
    else{
      print("Previous best sites and current best sites")
      print(best_iter_idx)
      print(site_idx)
      best_iter_idx <- site_idx
      print("Previous optimal survey effort and new optimal effort")
      print(optimal_visits)
      print(possible_visits)
      # Need to track if there is a change in visits over the course of full iteration
      optimal_visits <- possible_visits
    }
    # Print run time per exchange
    cur_time <- Sys.time()
    run_time <- cur_time - start_time
    print(paste("Current run time is", run_time))
  }
  
  v_list[[r_start]] <- v_vec
  best_site_mat[r_start,] <- best_iter_idx
  optimal_visit_mat[r_start,] <- optimal_visits
  best_v[r_start] <- current_v_est
}
end_time <- Sys.time()
run_time <- end_time - start_time
print("Total run time:")
print(run_time)


# Plot the convergence of V(D)
v_concat <- c()
x_concat <- c()
rep_labels <- c()
# Format v for data frame
for(i in 1:random_starts){
  v_concat <- c(v_concat, v_list[[i]])
  l_vec <- rep(paste("y", i, sep=""), length(v_list[[i]]))
  x_concat <- c(x_concat, 1:length(l_vec))
  rep_labels <- c(rep_labels, l_vec)
}

v_df <- data.frame(x=x_concat, v=v_concat, r=rep_labels)
fig_name <- file.path(fig_dir, "exchange_convergence.png")
p <- ggplot(data=v_df, aes(x=x, y=v, colour=r)) +
  geom_line() +
  theme_bw()
print(p)
ggsave(fig_name, plot=p, dpi=300, width=7, height=6, units="cm")

# Plot best sites
for(rs in 1:random_starts){
  title <- paste("PO data and Optimal sites from random init ", rs, "\n with V(D)=", best_v[rs], sep="")
  #p <- plot_sites(sampling_surface, best_site_mat[rs, ], title) 
  p <- plot_po_optimal_sites(sampling_surface, r_po_data, best_site_mat[rs,], optimal_visit_mat[rs,], title)
  fig_name <- file.path(fig_dir, paste("optimal_sites_random_start-", rs, ".png", sep=""))
  ggsave(fig_name, plot=p, dpi=300, width=7, height=6, units="cm")
}

print("V list")
print(v_list)
print("Best sites")
print(best_site_mat)
print("Optimal visits")
print(optimal_visit_mat)
print("best V")
print(best_v)
print("Avg V(D)")
print(sum(best_v) / random_starts)

write_results(random_starts, best_v, best_site_mat, optimal_visit_mat, v_df, exp_dir, exp_name)

# End cluster
stopCluster(clust)

